# Generated by Django 3.1.7 on 2021-03-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='picture',
            field=models.FileField(default='', upload_to='recipes/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.CharField(max_length=1000),
        ),
    ]
